FROM node:12

ENV WEBSITE_URL $WEBSITE_URL
ENV COMMAND_PREFIX $COMMAND_PREFIX
ENV DISCORD_TOKEN $DISCORD_TOKEN
ENV POSTGRES_HOST $POSTGRES_HOST
ENV POSTGRES_USER $POSTGRES_USER
ENV POSTGRES_PASSWORD $POSTGRES_PASSWORD
ENV POSTGRES_DB $POSTGRES_DB

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run compile

EXPOSE 8080

CMD ["node", "./dist/index.js"]